apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xcdpvf37u-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c030032be0.9t2g.p3.openshiftapps.com/rhtap/rhtap-qe:43b45bfce713c95174779bf137f8ead233ef3d16@sha256:ac62e4660824709e7f5a8502914f74c96ef5c7d2ad51717404bbe802941c7275
          name: container-image
